routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('admincp');
});

Route::get('/test','\Users\Http\controllers\Backend\UserController@index');
Auth::routes();

#======================================= Admin Area ===========================================
#==============================================================================================

# ========== admin Auth Area ==============================================
Route::get('admincp/login','Admin\LoginController@showLoginForm');
Route::post('admincp/login','Admin\LoginController@login')->name('admin.login');
Route::post('admincp/password/email','Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::post('admincp/password/reset','Admin\ResetPasswordController@reset')->name('admin.password.update');
Route::get('admincp/password/reset','Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::get('admincp/password/reset/{token}','Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
# =====================================================================

Route::group(['prefix' => 'admincp', 'middleware' => ['admin','auth:admin']], function () {

    Route::get('logout','Admin\LoginController@logout')->name('admin.logout');

    Route::get('/', function () {
        return view('admin.home.index');
    });


    // first controller to test standard pages
    Route::resource('testArea', 'Admin\FirstController');
    Route::get('testArea/{id}/delete', 'Admin\FirstController@destroy');

    #============================ Roles Area =================================
    Route::resource('roles', 'RoleController');
    Route::get('roles/users/{roleName}', 'RoleController@UsersHasRole');

    #============================ Users Area =================================
    Route::resource('users', 'UserController');

    #=========================== Site Settings Area ==================================
    Route::resource('offers','Admin\OfferController');

    Route::resource('orders','Admin\OrderController');

    Route::resource('images','Admin\ImageController');

    Route::resource('colors','Admin\ColorController');

    Route::resource('catogeries','Admin\CatogeryController');

    Route::resource('sliders','Admin\SliderController');

    Route::resource('settings','Admin\SettingsController');

    Route::resource('contact_us','Admin\ContactusController');

    Route::resource('user','Admin\UserController');

    Route::resource('questions','Admin\QuestionController');

    Route::resource('products','Admin\ProductController');

    Route::resource('pages','Admin\StaticpageController');

    Route::resource('admins','Admin\AdminController');

    Route::resource('contacts','Admin\ContactController');

    Route::resource('statistics','Admin\StatisticsController');

    Route::resource('admincp','Admin\StatisticsController');

    Route::resource('platforms','Admin\PlatformController');

    Route::resource('stores','Admin\StoreController');

    Route::resource('advertisements','Admin\StoreController');

});

Route::get('testtt', function () {
    return view('admin.testt');
});

resources/views/admin/page/create.blade.php
@extends('Admin.layouts.app')
@inject('model','App\Models\Static_page')
@section('title')
اضافه الصفحات
@endsection
@section('topBar')
	<li class="m-menu__item">
		<a href="{{url('admincp')}}" class="m-menu__link">
			<span class="m-menu__link-text">الرئيسية</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item">
		<a href="{{url('admincp/pages')}}" class="m-menu__link">
			<span class="m-menu__link-text">التحكم بالصفحات</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item" style="background: #e0deff;">
		<a href="javascript:;" class="m-menu__link">
			<span class="m-menu__link-text"></span>
			<i class="m-menu__hor-arrow la la-angle-down"></i>
		</a>
	</li>
@endsection

@section('header')
@endsection

@section('content')
	<!--begin::Portlet-->
	<div class="m-portlet">
		<div class="m-portlet__head">
			<div class="m-portlet__head-caption">
				<div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
					<h3 class="m-portlet__head-text">
						اضافه الصفحات
					</h3>
				</div>
			</div>
		</div>

	{!!Form::model($model,[
'action'=>'Admin\StaticpageController@store',
'files'=>true,
'class'=>'m-form m-form--fit m-form--label-align-right'
]) !!}



			<div class="col-lg-12">
			<label class=" col-form-label">   اسم  عربي</label>

			<div class="col-lg-9">


			{!!Form::text('name[ar]',null,[
            'class'=>'form-control m-input','placeholder'=>" اسم  عربي"
            ])!!}
			</div>
			</div>


		<div class="col-lg-12">
			<label class="col-form-label">   اسم  انجليزي</label>

			<div class="col-lg-9">


				{!!Form::text('name[en]',null,[
                'class'=>'form-control m-input','placeholder'=>" اسم  انجليزي"
                ])!!}
			</div>
		</div>



		<div class="col-lg-12">
			<label class="col-form-label">   النص عربي</label>

			<div class="col-lg-9">


				{!!Form::text('text[ar]',null,[
                'class'=>'form-control m-input','placeholder'=>" النص انجليزي"
                ])!!}
			</div>
		</div>



		<div class="col-lg-12">
			<label class="col-form-label">   النص انجليزي</label>

			<div class="col-lg-9">


				{!!Form::text('text[en]',null,[
                'class'=>'form-control m-input','placeholder'=>" النص  انجليزي"
                ])!!}
			</div>
		</div>




		<div class="col-lg-12">
				<label class="col-lg-1 col-form-label"> الصوره</label>


				<div class="col-lg-9">
					{!!Form::file('image',null,[
                'class'=>'form-control m-input'
                ])!!}
				</div>
			</div>
<br><br>
			<br>
			<div class='form-group' >
				<br>
				<button class="btn btn-primary" type="submit"> submit</button>
			</div>

		</div>




		{!! Form::close()!!}
	<!--end::Form-->
	</div>
	<!--end::Portlet-->
@endsection
@section('footer')
<script type="text/javascript">

</script>
@endsection

resources/views/admin/page/edit.blade.php
@extends('Admin.layouts.app')

@section('title')
	تعديل : الصفحات
@endsection
@section('topBar')
	<li class="m-menu__item">
		<a href="{{url('admincp')}}" class="m-menu__link">
			<span class="m-menu__link-text">الرئيسية</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item">
		<a href="{{url('admincp/pages')}}" class="m-menu__link">
			<span class="m-menu__link-text">التحكم بالصفحات</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item" style="background: #e0deff;">
		<a href="javascript:;" class="m-menu__link">
			<span class="m-menu__link-text">الصفحات</span>
			<i class="m-menu__hor-arrow la la-angle-down"></i>
		</a>
	</li>
@endsection

@section('header')
@endsection

@section('content')
	<!--begin::Portlet-->
	<div class="m-portlet">
		<div class="m-portlet__head">
			<div class="m-portlet__head-caption">
				<div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
					<h3 class="m-portlet__head-text">
						تعديل الصفحات
					</h3>
				</div>
			</div>
		</div>

	{!!Form::model($page,[
'action'=>['Admin\StaticpageController@update',$page->id],
'method'=>'put',
'files'=>true,
'class'=>'m-form m-form--fit m-form--label-align-right'
]) !!}



			<div class="col-lg-12">
			<label class="col-form-label">اسم  عربي</label>

			<div class="col-lg-9">


			{!!Form::text('name[ar]',getJsonData($page->name,'ar'),[
            'class'=>'form-control m-input','placeholder'=>"اسم  عربي"
            ])!!}
			</div>
			</div>



		<div class="col-lg-12">
			<label class=" col-form-label">اسم انجليزي</label>

			<div class="col-lg-9">


				{!!Form::text('name[en]',getJsonData($page->name,'en'),[
                'class'=>'form-control m-input','placeholder'=>"اسم  انجليزي"
                ])!!}
			</div>
		</div>





		<div class="col-lg-12">
			<label class=" col-form-label">النص عربي</label>

			<div class="col-lg-9">


				{!!Form::text('text[ar]',getJsonData($page->text,'ar'),[
                'class'=>'form-control m-input','placeholder'=>"النص عربي"
                ])!!}
			</div>
		</div>




		<div class="col-lg-12">
			<label class=" col-form-label">النص انجليزي</label>

			<div class="col-lg-9">


				{!!Form::text('text[en]',getJsonData($page->text,'en'),[
                'class'=>'form-control m-input','placeholder'=>"النص  انجليزي"
                ])!!}
			</div>
		</div>





		<div class="col-lg-12">
				<label class="col-lg-1 col-form-label"> الصوره</label>


				<div class="col-lg-9">
					{!!Form::file('image',null,[
                'class'=>'form-control m-input'
                ])!!}
				</div>
			</div>
<br><br>
			<br>
			<div class='form-group' >
				<br>
				<button class="btn btn-primary" type="submit"> submit</button>
			</div>

		</div>




		{!! Form::close()!!}
	<!--end::Form-->
	</div>
	<!--end::Portlet-->
@endsection
@section('footer')
<script type="text/javascript">

</script>
@endsection

resources/views/admin/page/index.blade.php
@extends('Admin.layouts.app')

@section('title')
	عرض الصفحات
@endsection
@section('topBar')
	<li class="m-menu__item">
		<a href="{{url('admincp')}}" class="m-menu__link">
			<span class="m-menu__link-text">الرئيسية</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item" style="background: #e0deff;">
		<a href="{{url('admincp\pages')}}" class="m-menu__link">
			<span class="m-menu__link-text">التحكم بالصفحات</span>
			<i class="m-menu__hor-arrow la la-angle-down"></i>
		</a>
	</li>
@endsection
@section('header')
	<!--begin::Page Vendors Styles -->
	{!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
	<!--end::Page Vendors Styles -->
@endsection

@section('content')
	<!-- END: Subheader -->
	<div class="m-content">
		<div class="m-portlet m-portlet--mobile">
			<div class="m-portlet__head">
				<div class="m-portlet__head-caption">
					<div class="m-portlet__head-title">
						<h3 class="m-portlet__head-text">التحكم بالصفحات
						</h3>
					</div>
				</div>
			</div>
		</div>
			<div class="m-portlet__body">

				<a href="{{url(route('pages.create'))}}" class="btn btn_primary btn btn-danger" ><i class=" fa fa-edit"></i>اضافه جديد</a>
<br><br> @include('error.error')
			@if($pages->count())
				@include('flash::message')
				<!--begin: Datatable -->
				<table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_users">
					<thead>
						<tr>
							<th>#</th>
							<th>الاسم  </th>
							<th> النص</th>

                             <th>الوقت</th>
							<th>الصوره</th>
                            <th>تعديل </th>
							<th>حذف</th>
						</tr>
					</thead>
					<tbody>
						@foreach($pages as $page)
						<tr class="debTr">
                            <th>{{$page->id}}</th>
							<th>{{getJsonData($page->name,'ar')}}</th>
							<th>{{getJsonData($page->text,'ar')}}</th>
                            <th>{{$page->created_at}}</th>

							<th> <img src="{{asset('/uploads/' . $page->image)}}" style="width:200px; height:100px"></th>
							<th>
								<a href="{{url('admincp/pages/'.$page->id.'/edit')}}" class="btn btn-brand m-btn editDeps">تعديل</a>

							</th>
							<th>
								<div class="form-group">


									{!! Form::open([

                                  'action'=>['Admin\StaticpageController@destroy',$page->id],
                                  'method'=>'delete'
                              ]) !!}

									<button class="btn btn-danger">حذف</button>

									{!! Form::close() !!}


								</div>

							</th>
						</tr>
						@endforeach
					</tbody>
				</table>

			</div>

		<!-- END EXAMPLE TABLE PORTLET-->
	</div>

	@else

		<div class="alert alert-danger">
			no data
		</div>
	@endif
</div>
	</div>
	</div>
@endsection
@section('footer')
	<!--begin::Page Vendors -->
	{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}
	{!! Html::script('admin/custom/js/countries.js') !!}
	<!--end::Page Vendors -->
<script type="text/javascript">
	var table = $('#m_table_users');
	// begin first table
	table.DataTable({
      	language: {
      	    aria: {
      	        sortAscending: ": ترتيب تصاعدى",
      	        sortDescending: ": ترتيب تنازلى"
      	    },
      	    emptyTable: "لا توجد اى بيانات متاحه",
      	    info: "إظهار _START_ إلى _END_ من _TOTAL_ حقل",
      	    infoEmpty: "لا توجد حقول",
      	    infoFiltered: "( الإجمالى _MAX_ حقل )",
      	    lengthMenu: "عدد الحقول : _MENU_",
      	    search: " بحث بإسم المستخدم :",
      	    zeroRecords: "لا توجد نتائج "
      	},

		responsive: true,
		order: [[0, "desc"]],
        lengthMenu: [[10, 20, 30, 50, -1], [10, 20, 30, 50, "الكل"]],
        pageLength: 10,
      	columnDefs: [{ "targets": [0,2,3,4], "searchable": false },{ "targets": [4], "orderable": false }]
	});


	$(document).on("click",".delUser",function(e) {
		e.preventDefault();
		var url = $(this).attr("href"),
		userId = $(this).data('id'),
		pData = {
			_token : "{{csrf_token()}}",
			_method : "delete"
		},
		ths = $(this);
		$.post(url,pData,function(data){
			toastrNotifyResponse(data);
			if(data.success){
				ths.closest('tr').remove();
			}
		});
	});
</script>
@endsection

    </div>