routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('admincp');
});

Route::get('/test','\Users\Http\controllers\Backend\UserController@index');
Auth::routes();

#======================================= Admin Area ===========================================
#==============================================================================================

# ========== admin Auth Area ==============================================
Route::get('admincp/login','Admin\LoginController@showLoginForm');
Route::post('admincp/login','Admin\LoginController@login')->name('admin.login');
Route::post('admincp/password/email','Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::post('admincp/password/reset','Admin\ResetPasswordController@reset')->name('admin.password.update');
Route::get('admincp/password/reset','Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::get('admincp/password/reset/{token}','Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
# =====================================================================

Route::group(['prefix' => 'admincp', 'middleware' => ['admin','auth:admin']], function () {

    Route::get('logout','Admin\LoginController@logout')->name('admin.logout');

    Route::get('/', function () {
        return view('admin.home.index');
    });


    // first controller to test standard pages
    Route::resource('testArea', 'Admin\FirstController');
    Route::get('testArea/{id}/delete', 'Admin\FirstController@destroy');

    #============================ Roles Area =================================
    Route::resource('roles', 'RoleController');
    Route::get('roles/users/{roleName}', 'RoleController@UsersHasRole');

    #============================ Users Area =================================
    Route::resource('users', 'UserController');

    #=========================== Site Settings Area ==================================
    Route::resource('offers','Admin\OfferController');

    Route::resource('orders','Admin\OrderController');

    Route::resource('images','Admin\ImageController');

    Route::resource('colors','Admin\ColorController');

    Route::resource('catogeries','Admin\CatogeryController');

    Route::resource('sliders','Admin\SliderController');

    Route::resource('settings','Admin\SettingsController');

    Route::resource('contact_us','Admin\ContactusController');

    Route::resource('user','Admin\UserController');

    Route::resource('questions','Admin\QuestionController');

    Route::resource('products','Admin\ProductController');

    Route::resource('pages','Admin\StaticpageController');

    Route::resource('admins','Admin\AdminController');

    Route::resource('contacts','Admin\ContactController');

    Route::resource('statistics','Admin\StatisticsController');

    Route::resource('admincp','Admin\StatisticsController');

    Route::resource('platforms','Admin\PlatformController');

    Route::resource('stores','Admin\StoreController');

    Route::resource('advertisements','Admin\StoreController');

});

Route::get('testtt', function () {
    return view('admin.testt');
});

app/Models/Store.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Store extends Model 
{

    protected $table = 'stores';
    public $timestamps = true;
    protected $fillable = array('user_id', 'logo', 'lng', 'lat');

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function catogery()
    {
        return $this->belongsTo('App\Models\Catogery');
    }

    public function ratings()
    {
        return $this->morphMany('App\Models\User', 'rateable');
    }

    public function images()
    {
        return $this->morphMany('App\Models\Image', 'imageable');
    }

    public function carts()
    {
        return $this->hasMany('App\Models\Cart');
    }

    public function messages()
    {
        return $this->hasMany('App\Models\Message');
    }

    public function platforms()
    {
        return $this->hasMany('App\Models\Platform');
    }

    public function products()
    {
        return $this->belongsToMany(Product::class,'product_store','product_id','store_id');
    }

}

app/Http/Controllers/Admin/StoreController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Store;
use App\Models\Image;

class StoreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $stores=Store::with(['catogery','images'])->get();

        return view('admin.store.index',compact('stores'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.store.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rule=[
            'namee'=>'required|max:191',
            'image'=>'required',


        ];

        $message=[

            'namee.requied'=>'this is required',
            'image.requied'=>'this is required'

        ];

        $this->validate($request,$rule,$message);


        $store=Store::create([
            'namee'=>$request->namee,
            'catogery_id'=>$request->catogery_id,


                           ]);



        $name = $request->file('image');
        $fileName = "";
//        $img = str_random(4) . $name->getClientOriginalName();
        $fileName = 'main_pro-' . time() . '-' . uniqid() . '.' . $name->getClientOriginalExtension();
        $destinationPath = 'uploads';
        $name->move($destinationPath, $fileName);
        $image = new Image();
        $image->image = $fileName;
        $image->imageable_id =$store->id;
        $image->imageable_type = 0;
        $image->save();



        flash()->message('تم إضافة المتجر بنجاح');

        return redirect(route('stores.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $store=Store::find($id);

        return view('admin.store.edit',compact('store'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $store=Store::find($id);

        $store->update([
            'namee'=>$request->namee,
            'catogery_id'=>$request->catogery_id,

                      ]);

        flash()->message('تم تعديل المتجر بنجاح');

        return redirect(route('stores.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $store=Store::find($id);
        $store->delete();
        flash()->message('تم حدف المتجر بنجاح');
        return back();

    }
}

resources/views/admin/admin/store/create.blade.php
@extends('Admin.layouts.app')
@inject('model','App\Models\Store')
@section('title')
اضافه متجر جديد
@endsection
@section('topBar')
	<li class="m-menu__item">
		<a href="{{url('admincp')}}" class="m-menu__link">
			<span class="m-menu__link-text">الرئيسية</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item">
		<a href="{{url('admincp/stores')}}" class="m-menu__link">
			<span class="m-menu__link-text">التحكم بالمتجر</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item" style="background: #e0deff;">
		<a href="javascript:;" class="m-menu__link">
			<span class="m-menu__link-text"></span>
			<i class="m-menu__hor-arrow la la-angle-down"></i>
		</a>
	</li>
@endsection

@section('header')
@endsection

@section('content')
	<!--begin::Portlet-->
	<div class="m-portlet">
		<div class="m-portlet__head">
			<div class="m-portlet__head-caption">
				<div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
					<h3 class="m-portlet__head-text">

					</h3>
				</div>
			</div>
		</div>

	{!!Form::model($model,[
'action'=>'Admin\StoreController@store',
'files'=>true,
'class'=>'m-form m-form--fit m-form--label-align-right'
]) !!}



		<div class="form-group">

		<div class="col-lg-12">
			<label class="col-form-label">اسم المتجر</label>

			<div class="col-lg-9">


				{!!Form::text('namee',null,[
                'class'=>'form-control m-input','placeholder'=>" اسم المتجر"
                ])!!}
			</div>
		</div>

		</div>


		<div class="col-lg-12">
			<div class="col-lg-9">

				<label class=" col-form-label">   اسم الصنف</label>
				@php $catogeries=App\Models\Catogery::all();	@endphp


				<select name='catogery_id' class="col-lg-12 form-control">
					@foreach($catogeries as $catogery)


						<option value="{{$catogery->id}}"> {{getJsonData($catogery->name,'ar')}} </option>



					@endforeach



				</select>
			</div>

		</div>



	<div class="form-group">
		<div class="col-lg-12">
			<label class="col-form-label">   الصوره الرئيسية</label>

			<div class="col-lg-9">

				<input type="file" id="file" class="file-input form-control" accept="image/*"
					   name="image">

			</div>
			</div>
		</div>


		<br><br>
			<br>
			<div class='form-group' >
				<br>
				<button class="btn btn-primary" type="submit"> submit</button>
			</div>

		</div>




		{!! Form::close()!!}
	<!--end::Form-->
	</div>
	<!--end::Portlet-->
@endsection
@section('footer')
<script type="text/javascript">

</script>
@endsection

resources/views/admin/admin/store/edit.blade.php
@extends('Admin.layouts.app')

@section('title')
	تعديل : المتجر
@endsection
@section('topBar')
	<li class="m-menu__item">
		<a href="{{url('admincp')}}" class="m-menu__link">
			<span class="m-menu__link-text">الرئيسية</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item">
		<a href="{{url('admincp/stores')}}" class="m-menu__link">
			<span class="m-menu__link-text">التحكم بالمتجر</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item" style="background: #e0deff;">
		<a href="javascript:;" class="m-menu__link">
			<span class="m-menu__link-text">تعديل :المتجر</span>
			<i class="m-menu__hor-arrow la la-angle-down"></i>
		</a>
	</li>
@endsection

@section('header')
@endsection

@section('content')
	<!--begin::Portlet-->
	<div class="m-portlet">
		<div class="m-portlet__head">
			<div class="m-portlet__head-caption">
				<div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
					<h3 class="m-portlet__head-text">
						تعديل :المتجر
					</h3>
				</div>
			</div>
		</div>

	{!!Form::model($store,[
'action'=>['Admin\StoreController@update',$store->id],
'method'=>'put',
'files'=>true,
'class'=>'m-form m-form--fit m-form--label-align-right'
]) !!}

		<div class="form-group">

			<div class="col-lg-12">
				<label class="col-form-label">اسم المتجر</label>

				<div class="col-lg-9">


					{!!Form::text('namee',null,[
                    'class'=>'form-control m-input','placeholder'=>" اسم المتجر"
                    ])!!}
				</div>
			</div>

		</div>

		<div class="form-group">
		<div class="col-lg-12">
			<div class="col-lg-9">

				<label class=" col-form-label">   اسم الصنف</label>
				@php $catogeries=App\Models\Catogery::all();	@endphp


				<select name='catogery_id' class="col-lg-12 form-control">
					@foreach($catogeries as $catogery)


						<option value="{{$catogery->id}}"> {{getJsonData($catogery->name,'ar')}} </option>



					@endforeach



				</select>
			</div>

		</div>

		</div>

		<div class="form-group">
			<div class="col-lg-12">
				<label class="col-form-label">   الصوره الرئيسية</label>

				<div class="col-lg-9">

					<input type="file" id="file" class="file-input form-control" accept="image/*"
						   name="image">

				</div>
			</div>
		</div>



<br><br>
			<br>
			<div class='form-group' >
				<br>
				<button class="btn btn-primary" type="submit"> submit</button>
			</div>

		</div>




		{!! Form::close()!!}
	<!--end::Form-->
	</div>
	<!--end::Portlet-->
@endsection
@section('footer')
<script type="text/javascript">

</script>
@endsection

resources/views/admin/admin/store/index.blade.php
@extends('Admin.layouts.app')

@section('title')
	عرض المتجر
@endsection
@section('topBar')
	<li class="m-menu__item">
		<a href="{{url('admincp')}}" class="m-menu__link">
			<span class="m-menu__link-text">الرئيسية</span>
			<i class="m-menu__hor-arrow la la-angle-left"></i>
		</a>
	</li>
	<li class="m-menu__item" style="background: #e0deff;">
		<a href="{{url('admincp\stores')}}" class="m-menu__link">
			<span class="m-menu__link-text">التحكم بالمتجر</span>
			<i class="m-menu__hor-arrow la la-angle-down"></i>
		</a>
	</li>
@endsection
@section('header')
	<!--begin::Page Vendors Styles -->
	{!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
	<!--end::Page Vendors Styles -->
@endsection

@section('content')
	<!-- END: Subheader -->
	<div class="m-content">
		<div class="m-portlet m-portlet--mobile">
			<div class="m-portlet__head">
				<div class="m-portlet__head-caption">
					<div class="m-portlet__head-title">
						<h3 class="m-portlet__head-text">التحكم بالمتجر
						</h3>
					</div>
				</div>
			</div>
		</div>
			<div class="m-portlet__body">

				<a href="{{url(route('stores.create'))}}" class="btn btn_primary btn btn-danger" ><i class=" fa fa-edit"></i>اضافه جديد</a>
<br><br> @include('error.error')
			@if($stores->count())
				@include('flash::message')
				<!--begin: Datatable -->
				<table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_users">
					<thead>
						<tr>
							<th>#</th>
							<th>اسم المتجر</th>
							<th>اسم التصنيف </th>
                             <th>الوقت</th>
							<th>الصوره</th>
                            <th>تعديل </th>
							<th>حذف</th>
						</tr>
					</thead>
					<tbody>
						@foreach($stores as $store)
						<tr class="debTr">
                            <th>{{$store->id}}</th>
							<th>{{isset($store->namee)?$store->namee :''}}</th>

							<th>{{isset($store->catogery->name)?getJsonData($store->catogery->name,'ar'):''}}</th>


							<th>{{$store->created_at}}</th>

							<th> <img src="{{asset('/uploads/' . $store->image)}}" style="width:200px; height:100px"></th>


							<th>
								<a href="{{url('admincp/stores/'.$store->id.'/edit')}}" class="btn btn-brand m-btn editDeps">تعديل</a>

							</th>
							<th>
								<div class="form-group">


									{!! Form::open([

                                  'action'=>['Admin\StoreController@destroy',$store->id],
                                  'method'=>'delete'
                              ]) !!}

									<button class="btn btn-danger">حذف</button>

									{!! Form::close() !!}


								</div>

							</th>
						</tr>
						@endforeach
					</tbody>
				</table>

			</div>

		<!-- END EXAMPLE TABLE PORTLET-->
	</div>

	@else

		<div class="alert alert-danger">
			no data
		</div>
	@endif
</div>
	</div>
	</div>
@endsection
@section('footer')
	<!--begin::Page Vendors -->
	{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}
	{!! Html::script('admin/custom/js/countries.js') !!}
	<!--end::Page Vendors -->
<script type="text/javascript">
	var table = $('#m_table_users');
	// begin first table
	table.DataTable({
      	language: {
      	    aria: {
      	        sortAscending: ": ترتيب تصاعدى",
      	        sortDescending: ": ترتيب تنازلى"
      	    },
      	    emptyTable: "لا توجد اى بيانات متاحه",
      	    info: "إظهار _START_ إلى _END_ من _TOTAL_ حقل",
      	    infoEmpty: "لا توجد حقول",
      	    infoFiltered: "( الإجمالى _MAX_ حقل )",
      	    lengthMenu: "عدد الحقول : _MENU_",
      	    search: " بحث بإسم المستخدم :",
      	    zeroRecords: "لا توجد نتائج "
      	},

		responsive: true,
		order: [[0, "desc"]],
        lengthMenu: [[10, 20, 30, 50, -1], [10, 20, 30, 50, "الكل"]],
        pageLength: 10,
      	columnDefs: [{ "targets": [0,2,3,4], "searchable": false },{ "targets": [4], "orderable": false }]
	});


	$(document).on("click",".delUser",function(e) {
		e.preventDefault();
		var url = $(this).attr("href"),
		userId = $(this).data('id'),
		pData = {
			_token : "{{csrf_token()}}",
			_method : "delete"
		},
		ths = $(this);
		$.post(url,pData,function(data){
			toastrNotifyResponse(data);
			if(data.success){
				ths.closest('tr').remove();
			}
		});
	});
</script>
@endsection

    </div>